version: '3.3'
services:
  db:
    image: postgres
    container_name: vfuk_sonar_db
    restart: always
    volumes:
      - $PWD/.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
 
  sonarqube:
    build: $PWD/package/sonar
    image: vfuk/sonarqube-dev
    container_name: vfuk_sonar_dev
    restart: always
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - $PWD./.docker/sonar:/opt/sonarqube/data
    depends_on:
       - db
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar